### ISSUE TITLE
gracefully handle tplink.login() failure

### ISSUE THREAD

**Issue by blaskovicz** [adumont/tplink-cloud-api#18]
If login fails to return a token, it throws the error:
`(node:3353) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'token' of undefined`

Rather than the actual response error (for example, I didn't pass any params):
`{ error_code: -20104, msg: 'Parameter doesn\'t exist' }`

**Comment by ColinMcNeil** [comment]
This repo hasn't been updated since April...
https://github.com/adumont/tplink-cloud-api/pull/17
If you want to fork it, I would also like to PR this
https://github.com/adumont/tplink-cloud-api/pull/14

**Comment by blaskovicz** [comment]
I also found this repo, https://github.com/plasticrake/tplink-smarthome-api/, which looks very active but doesn't support cloud interactions out of the box. Another option is to add support there so we can merge these feature sets, since that repo is very active.

**Comment by ColinMcNeil** [comment]
That one is also much more than what I typically need it for, and also does not work with Webpack. Otherwise I would've stopped subscribing to notifications here.

**Comment by blaskovicz** [comment]
Understood. I was using it as a reference since I noticed some other good features that are implemented there but missing here. For example, when I do a device list, I'd like to see those devices come back as instantiated device objects so I can directly action on them (eg: powerOn, etc).

I took a look at your code! I'm trying to build a similar thing (dashboard for turning things on/off) but on a garmin watch (eg: I did this for nest https://github.com/blaskovicz/garmin-nest-camera-control)

**Comment by blaskovicz** [comment]
@ColinMcNeil have you noticed issues with device list returning stale data from tplink's api? For example, I was able to easily turn my LB120 on/off but the `status` stays at 1 in the response.

**Comment by blaskovicz** [comment]
forked to https://github.com/blaskovicz/tplink-cloud-api and did 3 things:
- switched to yarn
- prettiered the code
- added a bunch of helpers and error checking

**Comment by ColinMcNeil** [comment]
Yes, the return data is unreliable. You can send another request on a delay and it might give better updates?

**Comment by blaskovicz** [comment]
@ColinMcNeil I sent a request this morning after about 6 hours and it still says the light is on. This is going to be a big issue for my app if the results are never updated. :/

I ran into a similar issue with Nest API, but the cache latency wasn't forever bad...

Any ideas?

**Comment by blaskovicz** [comment]
We can move that discussion over here: https://github.com/blaskovicz/tplink-cloud-api/issues/3

**Comment by blaskovicz** [comment]
I realized that asking for the system info of a device (`system: { get_sysinfo: null }`), will return the actual state (`{light_state: { on_off: 0 }}`), whereas `getDeviceList` perpetually returns `{ status: 1}`

**Comment by blaskovicz** [comment]
added more functions for .powerOn and .powerOff for bulbs

**Comment by adumont** [comment]
Addressed in #19 by @blaskovicz (Thanks)
