### ISSUE TITLE
v0.4.0 isn't transpiled, and installs non-working

### ISSUE THREAD

**Issue by JonSilver** [adumont/tplink-cloud-api#31]
0.3.9 installed with a `distribution` folder under `tplink-cloud-api`, containing both `.ts` source files and transpiled `.js` files.

0.4.0 installs with the source `lib` folder, containing only the `.ts` source files.

**Comment by adumont** [comment]
Sorry, messed up. Will fix on Monday.

**Comment by adumont** [comment]
@JonSilver hopefully it's ok now in 0.4.1.
(Also I messed up with the versioning... it jumped to 0.4, that wasn't my intention :( sorry about that, I guess now it's probably worse to "unpublish" it)

**Comment by JonSilver** [comment]
Thanks for this @adumont.

Never mind the version number. In my experience semantic version oopses are fine as long as the docs make it clear there were no breaking changes. 🙂

**Comment by JonSilver** [comment]
Unfortunately. @adumont, the current 0.4.1 package installs unusable too. The .js files are in the `distribution` subfolder, with no `files` or `main` entry in `package.json` so a simple `require("tplink-cloud-api")` statement fails to load the library.

**Comment by adumont** [comment]
Hi Jon, I've been testing right now on a simple app. the
require("tplink-cloud-api") statement seems to load the library just fine.
In fact it is working.
You're right, the js files are in the distribution folder, but I have tried
to remove one js file (I'm testing with a hs100, so I have removed the
hs100.js file), and it failed. I have put it in place again, and it worked
again. So, it would prove that it's correctly loading the js file from
there. At least on my computer...

I'm sorry, I'm not an expert on that at all. So if you see anything that
can be enhanced don't hesitate to let me know.

**Comment by adumont** [comment]
Hi @JonSilver I've just pushed a new version, 0.5.1. This is the content:

```
npm notice 📦  tplink-cloud-api@0.5.1
npm notice === Tarball Contents === 
npm notice 35.1kB LICENSE                      
npm notice 1.8kB  distribution/api-utils.js    
npm notice 10.1kB distribution/device.js       
npm notice 10.6kB distribution/hs100.js        
npm notice 6.4kB  distribution/hs110.js        
npm notice 2.1kB  distribution/hs200.js        
npm notice 8.3kB  distribution/lb100.js        
npm notice 5.6kB  distribution/lb130.js        
npm notice 10.9kB distribution/tplink.js       
npm notice 1.7kB  package.json                 
npm notice 874B   distribution/api-utils.js.map
npm notice 2.9kB  distribution/device.js.map   
npm notice 2.2kB  distribution/hs100.js.map    
npm notice 984B   distribution/hs110.js.map    
npm notice 346B   distribution/hs200.js.map    
npm notice 1.6kB  distribution/lb100.js.map    
npm notice 663B   distribution/lb130.js.map    
npm notice 4.3kB  distribution/tplink.js.map   
npm notice 6.7kB  README.md                    
npm notice 299B   distribution/api-utils.d.ts  
npm notice 1.2kB  distribution/device.d.ts     
npm notice 828B   distribution/hs100.d.ts      
npm notice 485B   distribution/hs110.d.ts      
npm notice 352B   distribution/hs200.d.ts      
npm notice 709B   distribution/lb100.d.ts      
npm notice 451B   distribution/lb130.d.ts      
npm notice 1.0kB  distribution/tplink.d.ts     
npm notice === Tarball Details === 
npm notice name:          tplink-cloud-api                        
npm notice version:       0.5.1                                   
npm notice package size:  25.7 kB                                 
npm notice unpacked size: 118.4 kB                                
npm notice shasum:        697280b70634c79e84a000bb7b544fa64ac1a30b
npm notice integrity:     sha512-mhre05RysPbVM[...]G3B1/PflSAlOg==
npm notice total files:   27                                      
```

I've also added a `files` section to package.json:

```
  "files": [
    "/distribution/**/*"
  ],
  "types": "distribution/index.d.ts",
```

I hope that helps for you. I've tested here locally in a small app and it works for me.
