### ISSUE TITLE
Any support for  KP303 in the future?

### ISSUE THREAD

**Issue by markawes** [adumont/tplink-cloud-api#41]
It outputs like this and has 3 separate outlets each can be controlled on their own and have their own alias set

`{
    deviceType: 'IOT.SMARTPLUGSWITCH',
    role: 0,
    fwVer: '1.0.3 Build 191105 Rel.113122',
    appServerUrl: 'https://eu-wap.tplinkcloud.com',
    deviceRegion: 'eu-west-1',
    deviceId: 'secret',
    deviceName: 'Kasa Smart Power Strip',
    deviceHwVer: '1.0',
    alias: 'TP-LINK_Power Strip_A5E9',
    deviceMac: 'secret',
    oemId: '707DC0D8FE3A745AAC776E000DC1CF15',
    deviceModel: 'KP303(UK)',
    hwId: 'secret',
    fwId: '00000000000000000000000000000000',
    isSameRegion: true,
    status: 1
  },`

**Comment by adumont** [comment]
Hi @markawes , could you try this https://github.com/adumont/tplink-cloud-api/issues/27#issuecomment-642304749 . It's an attempt to support the HS300, but nobody tested it.

Download from https://github.com/adumont/tplink-cloud-api/releases/tag/0.6.2-next.2.

It might work for the KP303.

**Comment by markawes** [comment]
> Hi @markawes , could you try this [#27 (comment)](https://github.com/adumont/tplink-cloud-api/issues/27#issuecomment-642304749) . It's an attempt to support the HS300, but nobody tested it.
> 
> Download from https://github.com/adumont/tplink-cloud-api/releases/tag/0.6.2-next.2.
> 
> It might work for the KP303.

No luck.

**Comment by cjdshaw** [comment]
You need to add
context":{"child_ids":["ID"]}
to the call, where the ID is obtained from get_sysinfo. e.g.
{"context":{"child_ids":["8006871xxxxxxxxxxxxxxxxxxxxxxxxxxx"]},"system":{"set_relay_state":{"state":1}}}

**Comment by markawes** [comment]
> You need to add
> context":{"child_ids":["ID"]}
> to the call, where the ID is obtained from get_sysinfo. e.g.
> {"context":{"child_ids":["8006871xxxxxxxxxxxxxxxxxxxxxxxxxxx"]},"system":{"set_relay_state":{"state":1}}}

I have managed to get the childIDS to show but can't seem to set the state `let strip = await tplink.getHS110("8006xxxxxxx").getSystemInfo({"context":{"child_ids":["8006xxxxxxx"]},"system":{"set_relay_state":{"state":1}}})`

**Comment by markawes** [comment]
All sorted
