### ISSUE TITLE
SyntaxError: await is only valid in async functions and the top level bodies of modules

### ISSUE THREAD

**Issue by ndg63276** [adumont/tplink-cloud-api#46]
Hello,
I'm struggling to get started with this, I get:
```
pi@raspberrypi:~ $ node
Welcome to Node.js v15.12.0.
Type ".help" for more information.
> const { login } = require("tplink-cloud-api");
undefined
> const tplink = await login("me@gmail.com", "password");
const tplink = await login("me@gmail.com", "password");
               ^^^^^

Uncaught:
SyntaxError: await is only valid in async functions and the top level bodies of modules
```

Any idea? I'm pretty new to Node so apologies if this is a dumb question.

**Comment by adumont** [comment]
Did you run "npm install tplink-cloud-api"?

**Comment by ndg63276** [comment]
Yes, I think even the first line would fail without that!
```
pi@raspberrypi:~ $ npm list
pi@ /home/pi
└── tplink-cloud-api@0.8.1
```

**Comment by pgerman15** [comment]
So if this is just like a plain js file that you've written this into, you can't await something in the main execution of the file itself. You need to wrap your await calls in an async function and then call that function. Like so:

[https://imgur.com/a/ybqHaaf](url)

Edit: 
Alternatively, you could skip the async/await setup and use a promise instead.

`const loginPromise = login('test@test.com', 'password').then(result => { console.log('TP link: ', result) });`

**Comment by adumont** [comment]
Indeed, try to follow the example in the Readme.md
https://github.com/adumont/tplink-cloud-api#example.

**Comment by ndg63276** [comment]
Ah I see, like I say I'm quite new to node, so I don't fully get async/await. I followed the example in the Usage section - https://github.com/adumont/tplink-cloud-api#authenticate. Thanks for your help!
